# chat_completion/models/tools.py
from dataclasses import dataclass
from typing import Literal
from .base import BaseModel

@dataclass
class Function(BaseModel):
    """Represents a function that the model called."""
    name: str
    arguments: str

@dataclass
class ToolCall(BaseModel):
    """Represents a tool call generated by the model."""
    id: str
    type: Literal["function"]
    function: Function